:toc: macro
:toc-title:
:toclevels: 99

# ARK Server-Tools Tutorial

**Installation of multiple ark server instances in a crossark travel cluster.**

_(last document review: 2018/04/10)_

---

toc::[]

---

## 1. System Setup ##
**Operating System:** Debian 8 or derivates like Ubuntu, with sudo installed and root access.

If you don't have access to the root account, the installation works with sudo access rights. Just put a `sudo` in front of every root command (e.g. `sudo apt-get update && sudo apt-get upgrade`).

---

## 2. Important notice ##

### 2.1 Change these values ###

**Please change these values according to your setup.**

At least change the admin passwort in all instance config files to a really secure passwort.

* **ARK-Server username:** [red yellow-background]*ark*
* **ARK-Cluster ID:** [red yellow-background]*arkcluster*
* **Admin Passwort:** [red yellow-background]*123*

### 2.2 Server instances ###

**This tutorial will setup following server instances:**

* **Map:** TheIsland - **Instance:** theisland.cfg - **Ports:** 7777,7778,27015,32330 - **Password:** 123
* **Map:** TheCenter - **Instance:** thecenter.cfg - **Ports:** 7779,7780,27016,32331 - **Password:** none
* **Map:** Ragnarok - **Instance:** ragnarok.cfg - **Ports:** 7781,7782,27017,32332 - **Password:** none
* **Map:** ScorchedEarth - **Instance:** scorchedearth.cfg - **Ports:** 7783,7784,27018,32333 - **Password:** none
* **Map:** Aberration - **Instance:** aberration.cfg - **Ports:** 7785,7786,27019,32334 - **Password:** none

---

## 3. Install required packages ##

**In the first step, we install all required packages to run a full featured ARK-Server. To manage the server, we add a new sudo user to the system called [red yellow-background]#ark#. Please [red yellow-background]#change this name in every step# according to your setup.**

Switch to root user or user with sudo privileges (if you have no root access, don't forget to add `sudo` to all commands), update package repositories and system packages.
```
$ su
$ apt-get update && apt-get upgrade
```

Install all required packages to run ARK Server-Tools and steamcmd.
```
$ apt-get install perl-modules curl lsof libc6-i386 lib32gcc1 bzip2 nano htop
```

Add ARK-Server user and add the user to the sudo group [red yellow-background]#(change username if applicable)#.
```
$ adduser ark
$ adduser ark sudo
```

---

## 4. Prepare Linux system ##

### 4.1 /etc/sysctl.conf ###

Edit the _sysctl.conf_ file.
```
$ vim /etc/sysctl.conf
``` 

Add the following line at the very end - if not already present (press `i` for edit mode).
```
fs.file-max=100000
```
_Save and exit vim (press `ESC` &rarr; `:wq`)._

---

### 4.2 /etc/security/limits.conf ###

Edit the _limits.conf_ file.
```
$ vim /etc/security/limits.conf
``` 

Add following line above _# End of file_ - if not already present (press `i` for edit mode).
```
* soft nofile 100000
* hard nofile 100000
```
_Save and exit vim (press `ESC` &rarr; `:wq`)._

---

### 4.3 /etc/pam.d/common-session ###

Edit the _common-session_ file.
```
$ vim /etc/pam.d/common-session
```

Add following line above _# end of pam-auth-update config_ - if not already present (press `i` for edit mode).
```
session required pam_limits.so
```
_Save and exit vim (press `ESC` &rarr; `:wq`)._

---

## 5. Open firewall ports ##

**Configure _iptables_ system firewall.**

### 5.1 TCP ###

Configure TCP ports.
```
$ iptables -A INPUT -p tcp -m multiport --dports 7777:7786,27015:27019,32330:32335 -j ACCEPT
```

### 5.2 UDP ###

Configure UDP ports.
```
$ iptables -A INPUT -p udp -m multiport --dports 7777:7786,27015:27019 -j ACCEPT
```

---

## 6. Install ARK Server-Tools & steamcmd ##

**In this step we install the ARK Server-Tools and the steam command line tool steamcmd. Both are required to run and manage our ARK server instances efficiently and to keep all instances up-to-date.**

Download and install ARK Server-Tools [red yellow-background]#(change username if applicable)#, switch to the ARK-Server user [red yellow-background]#(again change username if applicable)# and goto home directory.
```
$ curl -sL http://git.io/vtf5N | bash -s ark --me
$ su - ark
```

Create and goto the steamcmd folder to download and extract steamcmd.
```
$ mkdir steamcmd
$ cd steamcmd
$ curl -sqL "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz" | tar zxvf -
```

While still in steamcmd directory, install arkmanager then goto ARK-Server user _home/ark/ARK_ directory [red yellow-background]#(change username if applicable)# and install steamcmd.
```
$ arkmanager install
$ cd /home/ark/ARK/
$ ./SteamCMDInstall.sh
```

---

## 7. Configure arkmanager ##

**Configure arkmanager.cfg to set defaults for all instances.**

Edit arkmanager configuration file.
```
$ sudo vim /etc/arkmanager/arkmanager.cfg
```

Add flags, options and more (press `i` for edit mode).
```
...
# config SteamCMD
steamcmd_user="ark"
...
# config environment
arkbackupdir="/home/ark/ARK-Backups"
arkStagingDir="/home/ark/ARK-Staging"
...
# ARK mods
ark_GameModIds="731604991"
...
```
_Save and exit vim (press `ESC` &rarr; `:wq`)._

These are the most important settings. See full example **https://github.com/cyrexx/ark-server-tools-tutorial/blob/master/arkmanager/arkmanager.cfg[arkmanager.cfg]** file.

---

## 8. Configure ARK-Server instances ##

**Create server folders to save hard linked references to the serverfiles for all instances (to save up disk space).**

Switch to ark server user home directory and create a folder for all servers (keeps the installation clean and structured).
```
$ cd
$ mkdir ARK-Servers
```

Create server folders.
```
$ mkdir ARK-Servers/TheIsland
$ mkdir ARK-Servers/TheCenter
$ mkdir ARK-Servers/ScorchedEarth
$ mkdir ARK-Servers/Ragarok
$ mkdir ARK-Servers/Aberration
```

Create hardlinks to all serverfiles for all instances and remove no longer required server files.
```
$ cp -al ARK/* ARK-Servers/TheIsland
$ cp -al ARK/* ARK-Servers/TheCenter
$ cp -al ARK/* ARK-Servers/ScorchedEarth
$ cp -al ARK/* ARK-Servers/Ragnarok
$ cp -al ARK/* ARK-Servers/Aberration

$ rm -r ARK/
```

Remove old SavedArks files and create new SavedArks folders.
```
$ rm -r ARK-Servers/TheIsland/ShooterGame/Save/SavedArks/*
$ rm -r ARK-Servers/TheCenter/ShooterGame/Save/SavedArks/*
$ rm -r ARK-Servers/ScorchedEarth/ShooterGame/Save/SavedArks/*
$ rm -r ARK-Servers/Ragnarok/ShooterGame/Save/SavedArks/*
$ rm -r ARK-Servers/Aberration/ShooterGame/Save/SavedArks/*

$ mkdir ARK-Servers/TheIsland/ShooterGame/Save/SavedArks/TheIsland
$ mkdir ARK-Servers/TheCenter/ShooterGame/Save/SavedArks/TheCenter
$ mkdir ARK-Servers/ScorchedEarth/ShooterGame/Save/SavedArks/ScorchedEarth
$ mkdir ARK-Servers/Ragnarok/ShooterGame/Save/SavedArks/Ragnarok
$ mkdir ARK-Servers/Aberration/ShooterGame/Save/SavedArks/Aberration
```

Create ARK Server backups folder.
```
$ mkdir ARK-Backups
$ mkdir ARK-Backups/TheIsland
$ mkdir ARK-Backups/TheCenter
$ mkdir ARK-Backups/ScorchedEarth
$ mkdir ARK-Backups/Ragnarok
$ mkdir ARK-Backups/Aberration
```

Create ARK staging and cluster folder.
```
$ mkdir ARK-Staging

$ mkdir ARK-Cluster
$ mkdir ARK-Cluster/clusterdata
```

### 8.1 TheIsland

Goto to arkmanager instances folder and copy the instance configuration file _main.cfg_ (with default settings) to _theisland.cfg_, to create a new customizable instance configuration.
```
$ cd /etc/arkmanager/instances/
$ sudo cp main.cfg theisland.cfg
```

Edit theisland instance config. Customize flags, options and more.
```
$ sudo vim theisland.cfg
```

Press `i` for edit mode.
```
arkserverroot="/home/ark/ARK-Servers/TheIsland"

serverMap="TheIsland" 
arkbackupdir="/home/ark/ARK-Backups/TheIsland"

ark_RCONPort="32330"
ark_SessionName="ARK Server - TheIsland"
ark_Port="7778"
ark_QueryPort="27015"
ark_ServerPassword="123"
ark_ServerAdminPassword="123"
ark_MaxPlayers="50"
ark_AltSaveDirectoryName="SavedArks/TheIsland"

arkopt_clusterid=arkcluster
arkopt_ClusterDirOverride=/home/ark/ARK-Cluster/clusterdata
```
_Save and exit vim (press `ESC` &rarr; `:wq`)._

These are the most important settings. See full example **https://github.com/cyrexx/ark-server-tools-tutorial/blob/master/arkmanager/instances/theisland.cfg[theisland.cfg]** file.

If you finished configuring the first instance (e.g. theisland), continue to copy the instance .cfg file for all other instances.

### 8.2 TheCenter

Copy _theisland.cfg_ (with custom settings) to _thecenter.cfg_, to create a new instance.
```
$ sudo cp theisland.cfg thecenter.cfg
```

Edit thecenter instance configuration file and customize all required options.
```
$ sudo vim thecenter.cfg
```

Press `i` for edit mode.
```
arkserverroot="/home/ark/ARK-Servers/TheCenter"

serverMap="TheCenter"
arkbackupdir="/home/ark/ARK-Backups/TheCenter"

ark_RCONPort="32331"
ark_SessionName="ARK Server - TheCenter"
ark_Port="7780"
ark_QueryPort="27016"
ark_ServerPassword=""
ark_AltSaveDirectoryName="SavedArks/TheCenter"
```

These are the most important settings. See full example **https://github.com/cyrexx/ark-server-tools-tutorial/blob/master/arkmanager/instances/thecenter.cfg[thecenter.cfg]** file.

### 8.3 ScorchedEarth

Copy _thecenter.cfg_ (with custom settings) to _scorchedearth.cfg_, to create a new instance.
```
$ sudo cp thecenter.cfg scorchedearth.cfg
```

Edit scorchedearth instance configuration file and customize all required options.
```
$ sudo vim scorchedearth.cfg
```

Press `i` for edit mode.
```
arkserverroot="/home/ark/ARK-Servers/ScorchedEarth"

serverMap="ScorchedEarth_P"
arkbackupdir="/home/ark/ARK-Backups/ScorchedEarth"

ark_RCONPort="32333"
ark_SessionName="ARK Server - ScorchedEarth"
ark_Port="7784"
ark_QueryPort="27018"
ark_ServerPassword=""
ark_AltSaveDirectoryName="SavedArks/ScorchedEarth"
```

These are the most important settings. See full example **https://github.com/cyrexx/ark-server-tools-tutorial/blob/master/arkmanager/instances/scorchedearth.cfg[scorchedearth.cfg]** file.

### 8.4 Ragnarok

Copy _thecenter.cfg_ (with custom settings) to _ragnarok.cfg_, to create a new instance.
```
$ sudo cp thecenter.cfg ragnarok.cfg
```

Edit ragnarok instance configuration file and customize all required options.
```
$ sudo vim ragnarok.cfg
```

Press `i` for edit mode.
```
arkserverroot="/home/ark/ARK-Servers/Ragnarok"

serverMap="Ragnarok"
arkbackupdir="/home/ark/ARK-Backups/Ragnarok"

ark_RCONPort="32332"
ark_SessionName="ARK Server - Ragnarok"
ark_Port="7782"
ark_QueryPort="27017"
ark_ServerPassword=""
ark_AltSaveDirectoryName="SavedArks/Ragnarok"
```

These are the most important settings. See full example **https://github.com/cyrexx/ark-server-tools-tutorial/blob/master/arkmanager/instances/ragnarok.cfg[ragnarok.cfg]** file.

### 8.5 Aberration

Copy _thecenter.cfg_ (with custom settings) to _aberration.cfg_, to create a new instance.
```
$ sudo cp thecenter.cfg aberration.cfg
```

Edit aberration instance configuration file and customize all required options.
```
$ sudo vim aberration.cfg
```

Press `i` for edit mode.
```
arkserverroot="/home/ark/ARK-Servers/Aberration"

serverMap="Aberration_P"
arkbackupdir="/home/ark/ARK-Backups/Aberration"

ark_RCONPort="32334"
ark_SessionName="ARK Server - Aberration"
ark_Port="7786"
ark_QueryPort="27019"
ark_ServerPassword=""
ark_AltSaveDirectoryName="SavedArks/Aberration"
```

These are the most important settings. See full example **https://github.com/cyrexx/ark-server-tools-tutorial/blob/master/arkmanager/instances/aberration.cfg[aberration.cfg]** file.

---

## 9. Install mods ##

**Install ARK mods created by the community.**

Stop all instances to install Mods.
```
$ arkmanager stop @all
```

Set the Mod Id(s) in the _arkmanager.cfg_ file.
```
$ vim /etc/arkmanager/arkmanager.cfg
``` 

Press `i` for edit mode (specify additional mods by Mod Id, separated by commas).
```
ark_GameModIds="731604991" 
```

Run the _installmods_ command to install the Mod(s) via arkmanager. Update mods and start all instances.
```
$ arkmanager installmods @all
$ arkmanager update --update-mods
$ arkmanager start @all
```

---

## 10. Monitoring

### 10.1 Server updates

**Monitor all server instances for updates.**

Install the arkmanager cronjob to check for updates every hour.
```
$ arkmanager install-cronjob --hourly update @all --saveworld --warn --update-mods
```

Show all cronjobs for ARK-Server user and check if the update cronjob was successfully added.
```
$ crontab -l
```

The command (`crontab -l`) should display:
```
0 * * * * /usr/local/bin/arkmanager --cronjob update @all  --saveworld --warn --update-mods --args  -- >/dev/null 2>&1
```

---

### 10.2 Restart server on failure

**Monitor all server processes and restart on failure.**

Go to ARK-Server user home directory and check if arkmanager is in `/usr/local/bin`, if not, adjust the path to arkmanager in the script (next step).
```
$ cd
$ whereis arkmanager
```

Example Output of `whereis arkmanager`:
```
arkmanager: /etc/arkmanager /usr/local/bin/arkmanager
```

Create the shell script (Note: do not use file extensions like .sh, because it's Debian policy to have scripts in packages that will be placed in one of the bin folders to not have extensions).
```
$ vim ark-watchdog
```

Press `i` for edit mode and enter following script (change the arkmanager folder _/usr/local/bin_ - according to the results of `whereis arkmanager` - if arkmanager is not in _/usr/local/bin/arkmanager_):
```
#!/bin/bash

if [ ! `pgrep -f Port=7777` ] ; then
/usr/local/bin/arkmanager restart @theisland
fi
if [ ! `pgrep -f Port=7779` ] ; then
/usr/local/bin/arkmanager restart @thecenter
fi
if [ ! `pgrep -f Port=7781` ] ; then
/usr/local/bin/arkmanager restart @ragnarok
fi
if [ ! `pgrep -f Port=7783` ] ; then
/usr/local/bin/arkmanager restart @scorchedearth
fi
if [ ! `pgrep -f Port=7785` ] ; then
/usr/local/bin/arkmanager restart @aberration
fi
```
_Save and exit vim (press `ESC` &rarr; `:wq`)._

The script checks if the specified regular expression (e.g. Port=7777) matches with parts of the command line argument of a running process. If no process command line argument matches the given text, it will restart the affected server instance. You can change the regular expression (regex) to use server names or any other server unique text from the command line argument. E.g. `pgrep -f TheIsland` or `pgrep -f "ShooterGameServer TheCenter"`. But because it is pretty unlikely to have a second process with the same port command argument in the process name, I like to use to the port number of an ARK-Server to check if its process is running.

Show full command the server was started with.
```
$ ps axuwww
```

The desired output looks like (example):
```
...
/home/ark/ARK-Servers/TheIsland/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland?RCONEnabled=True?RCONPort=32330?SessionName=ARK Server - TheIsland?Port=7777?QueryPort=27015?ServerPassword=123?ServerAdminPassword=123?MaxPlayers=50?AltSaveDirectoryName=SavedArks/TheIsland?DifficultyOffset=1.000000?HarvestAmountMultiplier=1.2?ServerPVE=False?AllowFlyingStaminaRecovery=True?bRawSockets?AllowAnyoneBabyImprintCuddle=True?DisableWeatherFog=True?GameModIds=731604991?listen -clusterid=arkcluster -ClusterDirOverride=/home/ark/ARK-Cluster/clusterdata -NoTransferFromFiltering -noantispeedhack
...
```

Make the script executable, link watchdog script to the bin folder [red yellow-background]#(change username if applicable)# and add watchdog cron job to check servers every 10 minutes [red yellow-background]#(change username if applicable)#.
```
$ chmod u+x ark-watchdog
$ sudo ln -s /home/ark/ark-watchdog /usr/bin/
$ crontab -l | { cat; echo "*/10 * * * * /home/ark/ark-watchdog"; } | crontab -
```
Check out https://crontab.guru/, if you want to change the interval.

Show all cronjobs for ARK-Server user and check if the ark-watchdog cronjob was added successfully.
```
$ crontab -l
```

The command `crontab -l` should now display:
```
0 * * * * /usr/local/bin/arkmanager --cronjob update @all  --saveworld --warn --update-mods --args  -- >/dev/null 2>&1
*/10 * * * * /home/ark/ark-watchdog
```

Stop an ARK-Server to test the monitoring script.
```
$ arkmanager stop @theisland
$ ark-watchdog
```
Your server should be restarting.

If your server does not restart, check the path to arkmanager (`whereis arkmanager`) and the regex to identify the ARK-Servers (see script description).

---

**DONE & HAVE FUN**

---

## 11. Useful commands, files and links ##

**A list of useful commands to manage your server instances.**

### 11.1 Commands for _@all_ instances ###

```
$ arkmanager start @all   # Start all instances.
$ arkmanager stop @all    # Stop all instances.
$ arkmanager restart @all # Restart all instances.
$ arkmanager update @all  # Update all instances, if update is available.
$ arkmanager status @all  # Check the status of all instances.
```

### 11.2 Commands for a _@single_ instance ###

```
$ arkmanager start @theisland   # Start specified instance.
$ arkmanager stop @theisland    # Stop specified instance.
$ arkmanager restart @theisland # Restart specified instance.
$ arkmanager update @theisland  # Update specified instance, if update is available.
$ arkmanager status @theisland  # Check the status of the specified instance.
```

### 11.3 Available instances ###

* @theisland
* @thecenter
* @ragnarok
* @scorchedearth
* @aberration

### 11.4 LinuxGame.ini and GameUserSettings.ini ###

**This is the location of the two most important ARK-Server files, _LinuxGame.ini_ (often reffered to as Game.ini) and _GameUserSettings.ini_ (often reffered to as GUS.ini).**

Path to (edit) _LinuxGame.ini_ [red yellow-background]#(change username if applicable)#.
```
$ vim /home/ark/ARK-Servers/TheIsland/ShooterGame/Config/Linux/LinuxGame.ini
```

Path to (edit) _GameUserSettings.ini_ [red yellow-background]#(change username if applicable)#.
```
$ vim /home/ark/ARK-Servers/TheIsland/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini
```

---

## 12. Create a new server with different map

Switch to ARK-Server user [red yellow-background]#(change username if applicable)# and create the new server folder.
```
$ su - ark
$ mkdir ARK-Servers/NewServer
```

Hardlink server files, create new SavedArks and backup folder and remove old SavedArks folder.
```
$ cp -al ARK-Servers/TheIsland/* ARK-Servers/NewServer/
$ mkdir ARK-Backups/NewServer
$ mkdir ARK-Servers/NewServer/ShooterGame/Save/SavedArks/NewServer
$ rm -r ARK-Servers/NewServer/ShooterGame/Save/SavedArks/TheIsland
```

Switch to arkmanager instances folder, create a new instance and edit instance configuration.
```
$ cd /etc/arkmanager/instances/
$ cp theisland.cfg newserver.cfg
$ vim newserver.cfg
```

What to change (press `i` for edit mode)?

```
arkserverroot="/home/ark/ARK-Servers/NewServer" # Ark server root.
serverMap="NewMap"                              # The new map.
arkbackupdir="/home/ark/ARK-Backups/NewServer"  # Set backup directory.
ark_RCONPort="32335"                            # Set to an unused port number.
ark_SessionName="ARK Server - NewServer"        # Set ARK session name.
ark_Port="7788"                                 # Set to an unused port number.
ark_QueryPort="27020"                           # Set to an unused port number.
ark_AltSaveDirectoryName="SavedArks/NewServer"  # Set the new save directory.
ark_ServerAdminPassword="newserverpassword"     # Set admin passwort.
```

Start the new server.
```
$ arkmanager start @newserver
```

The new server will automatically join the existing cluster.

---

## 13. TODO ##

- [x] Add tutorial README.adoc
- [x] Add config files and demo configs
- [x] Test tutorial with sudo access rights
- [ ] Add links to sources and wikis
- [ ] Collect feedback
