:toc: macro
:toc-title:
:toclevels: 99

# ARK Server-Tools Tutorial
**ARK Server-Tools for Linux - Installation of multiple ark server instances in a crossark travel cluster.**

In this tutorial you will learn how to setup and manage multiple ark servers with enabled crossark travel.

toc::[]

## 1. System Setup ##
**Operating System:** Debian 8 or derivates like Ubuntu, with sudo installed and root access.

The installation may work with sudo access rights, but I haven't tested it yet. Just put a `sudo` in front of every root command if you don't have root access (e.g. `sudo apt-get update && sudo apt-get upgrade`).

## 2. Important notice ##
**_Please change these values according to your setup:_**

* ARK-Server username: `ARK_SERVER_USERNAME`
* ARK-Cluster ID: `ARK_CLUSTER_ID`

**This tutorial will setup following server instances:**

* Map: `TheIsland` - Instance: `theisland.cfg` - Ports: `7777,7778,27015,32330`
* Map: `TheCenter` - Instance: `thecenter.cfg` - Ports: `7779,7780,27016,32331`
* Map: `Ragnarok` - Instance: `ragnarok.cfg` - Ports: `7781,7782,27015,32332`
* Map: `ScorchedEarth` - Instance: `scorchedearth.cfg` - Ports: `7783,7784,27015,32333`
* Map: `Aberration` - Instance: `aberration.cfg` - Ports: `7785,7786,27015,32334`

## 3. Install required packages and add ARK-Server user ##
`su` :: Switch to root user.

`apt-get update && apt-get upgrade` :: Update package repository and system packages.

`apt-get install perl-modules curl lsof libc6-i386 lib32gcc1 bzip2 nano htop` :: Install all required packages.

`adduser ARK_SERVER_USERNAME` :: Add ARK-Server user (change **ARK_SERVER_USERNAME**), choose a strong password, other fields can be left blank.

`adduser ARK_SERVER_USERNAME sudo` :: Add the ARK-Server user to the sudo group.

## 4. Configure and prepare Linux system ##
`vim /etc/sysctl.conf` :: Edit the _sysctl.conf_ file. Add the following line at the very end - if not already present (press `i` for edit mode):
```
fs.file-max=100000
```
_Save and exit vim (press `ESC` &rarr; `:wq`)._

`vim /etc/security/limits.conf` :: Edit the _limits.conf_ file. Add following line above _# End of file_ - if not already present (press `i` for edit mode):
```
* soft nofile 100000
* hard nofile 100000
```
_Save and exit vim (press `ESC` &rarr; `:wq`)._

`vim /etc/pam.d/common-session` :: Edit the _common-session_ file. Add following line above _# end of pam-auth-update config_ - if not already present (press `i` for edit mode):
```
session required pam_limits.so
```
_Save and exit vim (press `ESC` &rarr; `:wq`)._

## 5. Open firewall ports ##
**Short version (recommended)**
```
iptables -A INPUT -p tcp -m multiport --dports 7777:7786,27015:27019,32330:32335 -j ACCEPT
iptables -A INPUT -p udp -m multiport --dports 7777:7786,27015:27019 -j ACCEPT
```
**Long version**
```
iptables -A INPUT -p tcp --dport 7777:7786 -j ACCEPT
iptables -A INPUT -p udp --dport 7777:7786 -j ACCEPT
iptables -A INPUT -p tcp --dport 27015:27019 -j ACCEPT
iptables -A INPUT -p udp --dport 27015:27019 -j ACCEPT
iptables -A INPUT -p tcp --dport 32330:32335 -j ACCEPT
```

## 6. Install ARK Server-Tools and steamcmd (required for ARK servers) ##
Download and install ARK Server-Tools:
```
curl -sL http://git.io/vtf5N | bash -s ARK_SERVER_USERNAME --me
```
Switch to the ARK-Server user:
```
su ARK_SERVER_USERNAME
```
Go to home directory:
```
cd ~
```
Create the steamcmd folder:
```
mkdir steamcmd
```
Switch to steamcmd folder:
```
cd steamcmd
```
Download and extract steamcmd:
```
curl -sqL "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz" | tar zxvf -
```
While still in steamcmd directory, install arkmanager:
```
arkmanager install
```
Install steamcmd:
```
cd /home/ARK_SERVER_USERNAME/ARK/
./SteamCMDInstall.sh
```

## 7. Configure arkmanager and ARK-Server instances ##
Switch back to root user:
```
exit
```
Configure arkmanager:
```
vim /etc/arkmanager/arkmanager.cfg
```
Add flags, options and more (press `i` for edit mode):
```
arkflag_log=true
arkflag_NoBattleEye=true
```
Save and exit vim (press `ESC` &rarr; `:wq`).

## 8. Configure default instance ##
Switch to instances folder:
```
cd /etc/arkmanager/instances/
```
Copy `main.cfg` (with default settings) to your new instance:
```
cp main.cfg NEW_SERVER_INSTANCE.cfg
```
Edit your new config:
```
vim NEW_SERVER_INSTANCE.cfg
```
Add flags, options and more (press `i` for edit mode):
```
arkflag_log=true
arkflag_NoBattleEye=true
```
Save and exit vim (press `ESC` &rarr; `:wq`).

## 9. Install mods ##
Switch to ARK-Server user:
```
su ARK_SERVER_USERNAME
```
Install the mods:
```
arkmanager installmods
```
Start the ARK-Sever:
```
arkmanager start
```

## 10 Configure autorestart on servercrash ##
Create the file `ark-watchdog`:
```
sudo vim ~/ARK/ShooterGame/Binaries/ark-watchdog
```
Enter following script (press `i` for edit mode):
```
#!/bin/bash
while true
do
if [ ! `pgrep ShooterGameServer` ] ; then
/usr/bin/ark-restart.sh
fi
sleep 30
done
```
Save and exit vim (press `ESC` &rarr; `:wq`).

Create the file `ark-restart.sh`:
```
sudo vim ~/ARK/ShooterGame/Binaries/ark-restart.sh
```
Enter following script (press `i` for edit mode):
```
cd /usr/local/bin
./arkmanager restart
```
Save and exit vim (press `ESC` &rarr; `:wq`).

Create a symlink to `ark-restart.sh`:
```
sudo ln -s /home/ARK_SERVER_USERNAME/ARK/ShooterGame/Binaries/ark-restart.sh /usr/bin/
```

## 11. Create a cronjob to check for updates every hour ##
Switch to root user:
```	
su
```
Install the cronjob:
```
arkmanager install-cronjob --hourly update @all --saveworld --warn --update-mods
```

### 11.1. Check if cronjob added successfully
Switch back to ARK-Server user:
```
exit
```
Show all cronjobs for ark and check if ark update cronjob added successfully:
```
crontab -e
```
The command (`crontab -e`) should display:
```
0 * * * * /usr/local/bin/arkmanager --cronjob update @all  --saveworld --warn --update-mods --args  -- >/dev/null 2>&1
```

---

**DONE ~ HAVE FUN**

---

## 12. Important arkmanager commands ##
Commands for `@all` instances:
```
arkmanager start @all // Start all instances
arkmanager stop @all // Stop all instances
arkmanager restart @all // ReStart all instances
arkmanager update @all // Check all instances for updates and install updates if available
arkmanager status @all // Check the online status of all instances
```

Commands for a `@single` instance:
```
arkmanager start @theisland // Start the specified instance
arkmanager stop @theisland // Stop the specified instance
arkmanager restart @theisland // Restart the specified instance
arkmanager update @theisland // Check the specified instance for updates and install updates if available
arkmanager status @theisland // Check the online status of the specified instance
```
(available instances: `@theisland`, `@thecenter`, `@ragnarok`, `@scorchedearth`, `@aberration`)

---

## 13. TODO ##
- [x] Add tutorial README.md
- [ ] Add config files and demo configs
- [ ] Test tutorial with sudo access rights
