:toc: macro
:toc-title:
:toclevels: 99

# ARK Server-Tools Tutorial

**Installation of multiple ark server instances in a crossark travel cluster.**

In this tutorial you will learn how to setup and manage multiple ark servers with enabled crossark travel.

This Tutorial will cover:

* Linux System preparation
* ARK Server installation
* Instance configuration
* Cluster-Setup
* Mod installation
* Monitoring all servers for updates
* Monitoring all server processes (auto restart on failure)

**_(last document review: 2018/04/09)_**

---

toc::[]

---

## 1. System Setup ##
**Operating System:** Debian 8 or derivates like Ubuntu, with sudo installed and root access.

If you don't have access to the root account, the installation works with sudo access rights. Just put a `sudo` in front of every root command (e.g. `sudo apt-get update && sudo apt-get upgrade`).

---

## 2. Important notice ##

### 2.1 Please change these values according to your setup ###

At least change the admin passwort in all instance config files to a really secure passwort.

* **ARK-Server username:** [red yellow-background]*ark*
* **ARK-Cluster ID:** [red yellow-background]*arkcluster*
* **Admin Passwort:** [red yellow-background]*123*

### 2.2 This tutorial will setup following server instances ###

* **Map:** TheIsland - **Instance:** theisland.cfg - **Ports:** 7777,7778,27015,32330
* **Map:** TheCenter - **Instance:** thecenter.cfg - **Ports:** 7779,7780,27016,32331
* **Map:** Ragnarok - **Instance:** ragnarok.cfg - **Ports:** 7781,7782,27017,32332
* **Map:** ScorchedEarth - **Instance:** scorchedearth.cfg - **Ports:** 7783,7784,27018,32333
* **Map:** Aberration - **Instance:** aberration.cfg - **Ports:** 7785,7786,27019,32334

---

## 3. Install required packages and add ARK-Server user ##

In the first step, we install all required packages to run a full featured ARK-Server. To manage the server, we add a new sudo user to the system called _ARK_SERVER_USERNAME_. Please **change this name** in every step according to your setup.

`su` :: Switch to root user or user with sudo privileges.
`apt-get update && apt-get upgrade` :: Update package repository and system packages.
`apt-get install perl-modules curl lsof libc6-i386 lib32gcc1 bzip2 nano htop` :: Install all required packages to run ARK Server-Tools and steamcmd.

---

`adduser ark` :: Add ARK-Server user [red yellow-background]#(change username if applicable)#, choose a strong password, other fields can be left blank.
`adduser ark sudo` :: Add the ARK-Server user to the sudo group [red yellow-background]#(change username if applicable)#.

---

## 4. Configure and prepare Linux system ##

### 4.1 /etc/sysctl.conf ###

`vim /etc/sysctl.conf` :: Edit the _sysctl.conf_ file. Add the following line at the very end - if not already present (press `i` for edit mode):
```
fs.file-max=100000
```
_Save and exit vim (press `ESC` &rarr; `:wq`)._

---

### 4.2 /etc/security/limits.conf ###

`vim /etc/security/limits.conf` :: Edit the _limits.conf_ file. Add following line above _# End of file_ - if not already present (press `i` for edit mode):
```
* soft nofile 100000
* hard nofile 100000
```
_Save and exit vim (press `ESC` &rarr; `:wq`)._

---

### 4.3 /etc/pam.d/common-session ###

`vim /etc/pam.d/common-session` :: Edit the _common-session_ file. Add following line above _# end of pam-auth-update config_ - if not already present (press `i` for edit mode):
```
session required pam_limits.so
```
_Save and exit vim (press `ESC` &rarr; `:wq`)._

---

## 5. Open firewall ports ##

Configure _iptables_ system firewall.

### 5.1 TCP ###

`iptables -A INPUT -p tcp -m multiport --dports 7777:7786,27015:27019,32330:32335 -j ACCEPT` :: Configure TCP ports.

### 5.2 UDP ###

`iptables -A INPUT -p udp -m multiport --dports 7777:7786,27015:27019 -j ACCEPT` :: Configure UDP ports.

---

## 6. Install ARK Server-Tools and steamcmd ##

In this step we install the ARK Server-Tools and the steam command line tool steamcmd. Both are required to run and manage our ARK server instances efficiently and to keep all instances up-to-date.

`curl -sL http://git.io/vtf5N | bash -s ark --me` :: Download and install ARK Server-Tools [red yellow-background]#(change username if applicable)#.

`su ark` :: Switch to the ARK-Server user [red yellow-background]#(change username if applicable)#.

`cd` :: Go to home directory.

`mkdir steamcmd` :: Create the steamcmd folder.

`cd steamcmd` :: Go to to steamcmd folder.

`curl -sqL "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz" | tar zxvf -` :: Download and extract steamcmd.

`arkmanager install` :: While still in steamcmd directory, install arkmanager.

`cd /home/ark/ARK/` :: Go to ARK-Server user home/ARK directory [red yellow-background]#(change username if applicable)#.

`./SteamCMDInstall.sh` :: Install steamcmd.

---

## 7. Configure arkmanager ##

`sudo vim /etc/arkmanager/arkmanager.cfg` :: Configure arkmanager. Add flags, options and more (press `i` for edit mode):
```
...
# config SteamCMD
steamcmd_user="ark"
...
# config environment
arkbackupdir="/home/ark/ARK-Backups"
arkStagingDir="/home/ark/ARK-Staging"
...
# ARK mods
ark_GameModIds="731604991"
...
```
_Save and exit vim (press `ESC` &rarr; `:wq`)._

These are the most important settings. See full example **https://github.com/cyrexx/ark-server-tools-tutorial/blob/master/arkmanager/arkmanager.cfg[arkmanager.cfg]** file.

---

## 8. Setup and configure ARK-Server instances ##

Create folders to save hard linked references to the serverfiles for all instances (we'll create the hardlinks to the server files in the next step).

`cd` :: Switch to ark server user home directory.
`mkdir ARK-Servers` :: Create folder for all servers - to keep the installation clean and structured.
`mkdir ARK-Servers/TheIsland` :: Create folder for TheIsland ARK Server.
`mkdir ARK-Servers/TheCenter` :: Create folder for TheCenter ARK Server.
`mkdir ARK-Servers/ScorchedEarth` :: Create folder for ScorchedEarth ARK Server.
`mkdir ARK-Servers/Ragarok` :: Create folder for Ragnarok ARK Server.
`mkdir ARK-Servers/Aberration` :: Create folder for Aberration ARK Server.

Create hardlinks to all serverfiles for all instances (to save up disk space).

`cp -al ARK/* ARK-Servers/TheIsland` :: Hardlink TheIsland serverfiles.
`cp -al ARK/* ARK-Servers/TheCenter` :: Hardlink TheCenter serverfiles.
`cp -al ARK/* ARK-Servers/ScorchedEarth` :: Hardlink ScorchedEarth serverfiles.
`cp -al ARK/* ARK-Servers/Ragnarok` :: Hardlink Ragnarok serverfiles.
`cp -al ARK/* ARK-Servers/Aberration` :: Hardlink Aberration serverfiles.

`rm -r ARK/` :: Remove no longer required server files.

Create ARK Server backups folder.

`mkdir ARK-Backups` :: Create the backup folder.
`mkdir ARK-Backups/TheIsland` :: Create TheIsland backup folder.
`mkdir ARK-Backups/TheCenter` :: Create TheCenter backup folder.
`mkdir ARK-Backups/ScorchedEarth` :: Create ScorchedEarth backup folder.
`mkdir ARK-Backups/Ragnarok` :: Create Ragnarok backup folder.
`mkdir ARK-Backups/Aberration` :: Create Aberration backup folder.

Create ARK staging and cluster folder.

`mkdir ARK-Staging` :: Create the staging folder.
`mkdir ARK-Cluster` :: Create the cluster folder.
`mkdir ARK-Cluster/clusterdata` :: Create the clusterdata folder.

### 8.1 TheIsland
`cd /etc/arkmanager/instances/` :: Switch to arkmanager instances folder.
`sudo cp main.cfg theisland.cfg` :: Copy `main.cfg` (with default settings) to theisland instance.
`sudo vim theisland.cfg` :: Edit theisland instance config. Customize flags, options and more (press `i` for edit mode):
```
<<file: /etc/arkmanager/instances/theisland.cfg>>

# config environment
arkserverroot="/home/ark/ARK-Servers/TheIsland"
...
# ARK server options
serverMap="TheIsland" 
arkbackupdir="/home/ark/ARK-Backups/TheIsland"
ark_RCONPort="32330"
ark_SessionName="ARK Server - TheIsland"
ark_Port="7778"
ark_QueryPort="27015"
ark_ServerPassword="123"
ark_ServerAdminPassword="123"
ark_MaxPlayers="50"
ark_AltSaveDirectoryName="SavedArks/TheIsland"
...
# ark cluster settings
arkopt_clusterid=arkcluster
arkopt_ClusterDirOverride=/home/ark/ARK-Cluster/clusterdata
...
```
_Save and exit vim (press `ESC` &rarr; `:wq`)._

These are the most important settings. See full example **https://github.com/cyrexx/ark-server-tools-tutorial/blob/master/arkmanager/instances/TheIsland.cfg[theisland.cfg]** file.

If you finished configuring the first instance (e.g. theisland), continue to copy the instance.cfg file for all other instances.

### 8.2 TheCenter

`sudo cp theisland.cfg thecenter.cfg` :: Copy `theisland.cfg` (with custom settings) to thecenter instance.
`sudo vim thecenter.cfg` :: Edit thecenter instance config (I removed the server passwort for this instance). Customize all required options for this instance (press `i` for edit mode):

```
<<file: /etc/arkmanager/instances/thecenter.cfg>>

# config environment
arkserverroot="/home/ark/ARK-Servers/TheCenter"
...
# ARK server options
serverMap="TheCenter"
arkbackupdir="/home/ark/ARK-Backups/TheCenter"
...
ark_RCONPort="32331"
ark_SessionName="ARK Server - TheCenter"
ark_Port="7780"
ark_QueryPort="27016"
ark_ServerPassword=""
ark_AltSaveDirectoryName="SavedArks/TheCenter"
```

These are the most important settings. See full example **https://github.com/cyrexx/ark-server-tools-tutorial/blob/master/arkmanager/instances/TheCenter.cfg[thecenter.cfg]** file.

### 8.3 ScorchedEarth

`sudo cp thecenter.cfg scorchedearth.cfg` :: Copy `thecenter.cfg` (with custom settings - no server passwort required) to scorchedearth instance.
`sudo vim scorchedearth.cfg` :: Edit scorchedearth instance config.

```
<<file: /etc/arkmanager/instances/scorchedearth.cfg>>

# config environment
arkserverroot="/home/ark/ARK-Servers/ScorchedEarth"
...
# ARK server options
serverMap="ScorchedEarth_P"
arkbackupdir="/home/ark/ARK-Backups/ScorchedEarth"
...
ark_RCONPort="32333"
ark_SessionName="ARK Server - ScorchedEarth"
ark_Port="7784"
ark_QueryPort="27018"
ark_ServerPassword=""
ark_AltSaveDirectoryName="SavedArks/ScorchedEarth"
```

These are the most important settings. See full example **https://github.com/cyrexx/ark-server-tools-tutorial/blob/master/arkmanager/instances/ScorchedEarth.cfg[scorchedearth.cfg]** file.

### 8.4 Ragnarok

`sudo cp thecenter.cfg ragnarok.cfg` :: Copy `thecenter.cfg` (with custom settings - no server passwort required) to ragnarok instance.
`sudo vim ragnarok.cfg` :: Edit ragnarok instance config.

```
<<file: /etc/arkmanager/instances/ragnarok.cfg>>

# config environment
arkserverroot="/home/ark/ARK-Servers/Ragnarok"
...
# ARK server options
serverMap="ScorchedEarth_P"
arkbackupdir="/home/ark/ARK-Backups/Ragnarok"
...
ark_RCONPort="32332"
ark_SessionName="ARK Server - Ragnarok"
ark_Port="7782"
ark_QueryPort="27017"
ark_ServerPassword=""
ark_AltSaveDirectoryName="SavedArks/Ragnarok"
```

These are the most important settings. See full example **https://github.com/cyrexx/ark-server-tools-tutorial/blob/master/arkmanager/instances/ragnarok.cfg[ragnarok.cfg]** file.

### 8.5 Aberration

`sudo cp thecenter.cfg aberration.cfg` :: Copy `thecenter.cfg` (with custom settings - no server passwort required) to aberration instance.
`sudo vim aberration.cfg` :: Edit aberration instance config.

```
<<file: /etc/arkmanager/instances/aberration.cfg>>

# config environment
arkserverroot="/home/ark/ARK-Servers/Aberration"
...
# ARK server options
serverMap="Aberration_P"
arkbackupdir="/home/ark/ARK-Backups/Aberration"
...
ark_RCONPort="32334"
ark_SessionName="ARK Server - Aberration"
ark_Port="7786"
ark_QueryPort="27019"
ark_ServerPassword=""
ark_AltSaveDirectoryName="SavedArks/Aberration"
```

These are the most important settings. See full example **https://github.com/cyrexx/ark-server-tools-tutorial/blob/master/arkmanager/instances/Aberration.cfg[aberration.cfg]** file.

---

## 9. Install mods ##

Set the Mod Ids in the _arkmanager.cfg_ and run the _installmods_ command.

`arkmanager stop @all` :: Stop all instances to install Mods.
`vim /etc/arkmanager/arkmanager.cfg` :: Adjust the config file and change following content, specify additional mods by Mod Id separated by commas:
```
ark_GameModIds="731604991" 
```
`arkmanager installmods @all` :: Install the Mod(s) via arkmanager.
`arkmanager update --update-mods` :: Update Mod(s)
`arkmanager start @all` :: Start all instances.

---

## 10. Monitoring

### 10.1 Server updates

Monitoring all servers for updates. Create a cronjob to check for updates every hour.

`arkmanager install-cronjob --hourly update @all --saveworld --warn --update-mods` :: Install the arkmanager cronjob.

`crontab -e` :: Show all cronjobs for ark and check if ark update cronjob added successfully.

The command (`crontab -l`) should display:
```
0 * * * * /usr/local/bin/arkmanager --cronjob update @all  --saveworld --warn --update-mods --args  -- >/dev/null 2>&1
```

---

### 10.2 Restart server on failure

Monitoring all server processes and restart on failure.

`cd` :: Go to ARK-Server user home directory.

`whereis arkmanager` :: Check if arkmanager is in `/usr/local/bin`, if not, adjust the path to arkmanager in the script (next step).

`vim ark-watchdog` :: Create the shell script (Note: do not use file extensions like .sh, because it's Debian policy to have scripts in packages that will be placed in one of the bin folders to not have extensions). Enter following script:

```
#!/bin/bash

if [ ! `pgrep -f Port=7777` ] ; then
/usr/local/bin/arkmanager restart @theisland
fi
if [ ! `pgrep -f Port=7779` ] ; then
/usr/local/bin/arkmanager restart @thecenter
fi
if [ ! `pgrep -f Port=7781` ] ; then
/usr/local/bin/arkmanager restart @ragnarok
fi
if [ ! `pgrep -f Port=7783` ] ; then
/usr/local/bin/arkmanager restart @scorchedearth
fi
if [ ! `pgrep -f Port=7785` ] ; then
/usr/local/bin/arkmanager restart @aberration
fi
```
_Save and exit vim (press `ESC` &rarr; `:wq`)._

The script checks if the specified regular expression (e.g. Port=7777) matches with parts of the command line argument of a running process. If no process command line argument matches the given text, it will restart the affected server instance. You can change the regular expression (regex) to use server names or any other server unique text from the command line argument. E.g. `pgrep -f TheIsland` or `pgrep -f "ShooterGameServer TheCenter"`. But because it is pretty unlikely to have a second process with the same port-text in the process name or arguments, I like to use to the Port number of the server to check if a particular process is running.

`ps axuwww` :: Show full command the server was started with. The desired output looks like (example):

```
...
/home/ark/ARK-Servers/TheIsland/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland?RCONEnabled=True?RCONPort=32330?SessionName=ARK Server - TheIsland?Port=7777?QueryPort=27015?ServerPassword=123?ServerAdminPassword=123?MaxPlayers=50?AltSaveDirectoryName=SavedArks/TheIsland?DifficultyOffset=1.000000?HarvestAmountMultiplier=1.2?ServerPVE=False?AllowFlyingStaminaRecovery=True?bRawSockets?AllowAnyoneBabyImprintCuddle=True?DisableWeatherFog=True?GameModIds=731604991?listen -clusterid=pvearkcluster -ClusterDirOverride=/home/ark/ARK-Cluster/clusterdata -NoTransferFromFiltering -noantispeedhack
...
```

`chmod u+x ark-watchdog` :: Make the script executable.

`sudo ln -s /home/ark/ark-watchdog /usr/bin/` :: Link watchdog script to the bin folder [red yellow-background]#(change username if applicable)#.

`crontab -l | { cat; echo "*/10 * * * * /home/ark/ark-watchdog"; } | crontab -` :: Add watchdog cron job and check servers every 10 minutes [red yellow-background]#(change username if applicable)#. Check out https://crontab.guru/, if you want to change the interval.

`crontab -e` :: Show all cronjobs for ark and check if ark update cronjob added successfully.

The command (`crontab -l`) should now display:
```
0 * * * * /usr/local/bin/arkmanager --cronjob update @all  --saveworld --warn --update-mods --args  -- >/dev/null 2>&1
*/10 * * * * /home/ark/ark-watchdog
```

---

**DONE & HAVE FUN**

---

## 11. Useful commands, files and links ##

### 11.1 Commands for _@all_ instances ###

`arkmanager start @all` :: Start all instances.
`arkmanager stop @all` :: Stop all instances.
`arkmanager restart @all` :: ReStart all instances.
`arkmanager update @all` :: Check all instances for updates and install updates if available.
`arkmanager status @all` :: Check the online status of all instances.

### 11.2 Commands for a _@single_ instance ###

`arkmanager start @theisland` :: Start the specified instance.
`arkmanager stop @theisland` :: Stop the specified instance.
`arkmanager restart @theisland` :: Restart the specified instance.
`arkmanager update @theisland` :: Check the specified instance for updates and install updates if available.
`arkmanager status @theisland` :: Check the online status of the specified instance.

### 11.3 Available instances ###

* @theisland
* @thecenter
* @ragnarok
* @scorchedearth
* @aberration

### 11.4 LinuxGame.ini and GameUserSettings.ini ###

This is the location of the two most important ARK-Server files, _LinuxGame.ini_ (often reffered to as Game.ini) and _GameUserSettings.ini_ (often reffered to as GUS.ini).

`vim /home/ark/ARK-Servers/TheIsland/ShooterGame/Config/Linux/LinuxGame.ini` :: Path to (edit) _LinuxGame.ini_ [red yellow-background]#(change username if applicable)#.
`vim /home/ark/ARK-Servers/TheIsland/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini` :: Path to (edit) _GameUserSettings.ini_ [red yellow-background]#(change username if applicable)#.

---

## 12. TODO ##

- [x] Add tutorial README.adoc
- [ ] Add config files and demo configs
- [ ] Test tutorial with sudo access rights
- [ ] Add more text to headlines
- [ ] Add links to sources and wikis
- [ ] Collect feedback
- [ ] Add steps to create config files for all instances with demo config options
