:toc: macro
:toc-title:
:toclevels: 99

# ARK Server-Tools Tutorial
**ARK Server-Tools for Linux - Installation of multiple ark server instances in a crossark travel cluster.**

In this tutorial you will learn how to setup and manage multiple ark servers with enabled crossark travel.

toc::[]

## 1. System Setup ##
**Operating System:** Debian 8 or derivates like Ubuntu, with sudo installed and root access.

The installation may work with sudo access rights, but I haven't tested it yet. Just put a `sudo` in front of every root command if you don't have root access (e.g. `sudo apt-get update && sudo apt-get upgrade`).

---

## 2. Important notice ##

### 2.1 Please change these values according to your setup ###

* **ARK-Server username:** `ARK_SERVER_USERNAME`
* **ARK-Cluster ID:** `ARK_CLUSTER_ID`

### 2.2 This tutorial will setup following server instances ###

* **Map:** TheIsland - **Instance:** theisland.cfg - **Ports:** 7777,7778,27015,32330
* **Map:** TheCenter - **Instance:** thecenter.cfg - **Ports:** 7779,7780,27016,32331
* **Map:** Ragnarok - **Instance:** ragnarok.cfg - **Ports:** 7781,7782,27015,32332
* **Map:** ScorchedEarth - **Instance:** scorchedearth.cfg - **Ports:** 7783,7784,27015,32333
* **Map:** Aberration - **Instance:** aberration.cfg - **Ports:** 7785,7786,27015,32334

---

## 3. Install required packages and add ARK-Server user ##

In the first step, we install all required packages to run a full fledged ARK-Server. To manage the server, we add a new user to the system called _ARK_SERVER_USERNAME_ and give that user sudo rights. Please change this name in every step according to your setup.

`su` :: Switch to root user.
`apt-get update && apt-get upgrade` :: Update package repository and system packages.
`apt-get install perl-modules curl lsof libc6-i386 lib32gcc1 bzip2 nano htop` :: Install all required packages.

---

`adduser ARK_SERVER_USERNAME` :: Add ARK-Server user (change **ARK_SERVER_USERNAME**), choose a strong password, other fields can be left blank.
`adduser ARK_SERVER_USERNAME sudo` :: Add the ARK-Server user to the sudo group.

---

## 4. Configure and prepare Linux system ##

`vim /etc/sysctl.conf` :: Edit the _sysctl.conf_ file. Add the following line at the very end - if not already present (press `i` for edit mode):
```
fs.file-max=100000
```
_Save and exit vim (press `ESC` &rarr; `:wq`)._

---

`vim /etc/security/limits.conf` :: Edit the _limits.conf_ file. Add following line above _# End of file_ - if not already present (press `i` for edit mode):
```
* soft nofile 100000
* hard nofile 100000
```
_Save and exit vim (press `ESC` &rarr; `:wq`)._

---

`vim /etc/pam.d/common-session` :: Edit the _common-session_ file. Add following line above _# end of pam-auth-update config_ - if not already present (press `i` for edit mode):
```
session required pam_limits.so
```
_Save and exit vim (press `ESC` &rarr; `:wq`)._

---

## 5. Open firewall ports ##

Configure _iptables_ system firewall.

`iptables -A INPUT -p tcp -m multiport --dports 7777:7786,27015:27019,32330:32335 -j ACCEPT` :: Configure TCP ports.
`iptables -A INPUT -p udp -m multiport --dports 7777:7786,27015:27019 -j ACCEPT` :: Configure UDP ports.

---

## 6. Install ARK Server-Tools and steamcmd (required for ARK servers) ##

`curl -sL http://git.io/vtf5N | bash -s ARK_SERVER_USERNAME --me` :: Download and install ARK Server-Tools (change **ARK_SERVER_USERNAME**).

`su ARK_SERVER_USERNAME` :: Switch to the ARK-Server user (change **ARK_SERVER_USERNAME**).

`cd ~` :: Go to home directory.

`mkdir steamcmd` :: Create the steamcmd folder.

`cd steamcmd` :: Go to to steamcmd folder.

`curl -sqL "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz" | tar zxvf -` :: Download and extract steamcmd.

`arkmanager install` :: While still in steamcmd directory, install arkmanager.

`cd /home/ARK_SERVER_USERNAME/ARK/` :: Go to ARK-Server user home/ARK directory (change **ARK_SERVER_USERNAME**).

`./SteamCMDInstall.sh` :: Install steamcmd.

---

## 7. Configure arkmanager and ARK-Server instances ##

`exit` :: Switch back to root user.
`vim /etc/arkmanager/arkmanager.cfg` :: Configure arkmanager. Add flags, options and more (press `i` for edit mode):
```
arkflag_log=true
arkflag_NoBattleEye=true
```
_Save and exit vim (press `ESC` &rarr; `:wq`)._

---

## 8. Configure default instance ##

`cd /etc/arkmanager/instances/` :: Switch to arkmanager instances folder.
`cp main.cfg NEW_SERVER_INSTANCE.cfg` :: Copy `main.cfg` (with default settings) to your new instance.
`vim NEW_SERVER_INSTANCE.cfg` :: Edit your new config. Add flags, options and more (press `i` for edit mode):
```
arkflag_log=true
arkflag_NoBattleEye=true
```
_Save and exit vim (press `ESC` &rarr; `:wq`)._

---

## 9. Install mods ##

`su ARK_SERVER_USERNAME` :: Switch to ARK-Server user (change **ARK_SERVER_USERNAME**).
`arkmanager installmods` :: Install the mods
`arkmanager start` :: Start the ARK-Sever

---

## 10. Configure autorestart on servercrash ##

`sudo vim ~/ARK/ShooterGame/Binaries/ark-watchdog` :: Create the file _ark-watchdog_. Enter following script (press `i` for edit mode):
```
#!/bin/bash
while true
do
if [ ! `pgrep ShooterGameServer` ] ; then
/usr/bin/ark-restart.sh
fi
sleep 30
done
```
_Save and exit vim (press `ESC` &rarr; `:wq`)._

---

`sudo vim ~/ARK/ShooterGame/Binaries/ark-restart.sh` :: Create the file _ark-restart.sh_. Enter following script (press `i` for edit mode):
```
cd /usr/local/bin
./arkmanager restart
```
_Save and exit vim (press `ESC` &rarr; `:wq`)._

---

`sudo ln -s /home/ARK_SERVER_USERNAME/ARK/ShooterGame/Binaries/ark-restart.sh /usr/bin/` :: Create a symlink to _ark-restart.sh_.

---

## 11. Create a cronjob to check for updates every hour ##

`su` :: Switch to root user.
`arkmanager install-cronjob --hourly update @all --saveworld --warn --update-mods` :: Install the arkmanager cronjob.

### 11.1 Check if cronjob added successfully ###

`exit` :: Switch back to ARK-Server user.
`crontab -e` :: Show all cronjobs for ark and check if ark update cronjob added successfully.

The command (`crontab -e`) should display:
```
0 * * * * /usr/local/bin/arkmanager --cronjob update @all  --saveworld --warn --update-mods --args  -- >/dev/null 2>&1
```

---

**DONE ~ HAVE FUN**

---

## 12. Important arkmanager commands ##

### 12.1 Commands for _@all_ instances ###

`arkmanager start @all` :: Start all instances.
`arkmanager stop @all` :: Stop all instances.
`arkmanager restart @all` :: ReStart all instances.
`arkmanager update @all` :: Check all instances for updates and install updates if available.
`arkmanager status @all` :: Check the online status of all instances.

### 12.2 Commands for a _@single_ instance ###

`arkmanager start @theisland` :: Start the specified instance.
`arkmanager stop @theisland` :: Stop the specified instance.
`arkmanager restart @theisland` :: Restart the specified instance.
`arkmanager update @theisland` :: Check the specified instance for updates and install updates if available.
`arkmanager status @theisland` :: Check the online status of the specified instance.

### 12.3 Available instances ###

* @theisland
* @thecenter
* @ragnarok
* @scorchedearth
* @aberration

---

## 13. TODO ##

- [x] Add tutorial README.md
- [ ] Add config files and demo configs
- [ ] Test tutorial with sudo access rights
